package com.coder.constants;

public interface LogConstants {

    String API_METHOD_REQUEST = "COM_10000";

    String COM_ERROR_LOG = "COM_10001";

    String COM_HTTP_REQUEST_LOG = "COM_10002";

    String COM_CREATE_CHAIN = "COM_10003";

    String COM_BLOCKCHAIN_HEALTH_CHECK_PARA = "COM_10004";

    String COM_BLOCKCHAIN_HEALTH_CHECK_RESULT = "COM_10005";

    String CLUSTER_NODE_INFO_INIT_BEGIN = "COM_10006";

    String CLUSTER_NODE_INFO_INIT_END = "COM_10007";

    String COM_ENDPOINT_SIGN_ERROR = "ERROR_10000";

    String COM_ABS_SIGN_ERROR = "ERROR_10001";

    String COM_PARTICIPANT_REDIS_NULL = "ERROR_10002";

    String COM_ZOO_CHILDREN_NODE_NULL = "ERROR_10003";

    String COM_SYNC_PARTICIPANT_REDIS_ERROR = "ERROR_10004";

    String COM_MONITOR_ERROR = "ERROR_10005";

    String CACHE_NO_COMMITTER_ERROR = "ERROR_10006";

    String CHAIN_INFO_NOT_FOUND = "ERROR_10007";

    String CHAIN_PARTICIPANT_INFO_NOT_COMPLETE_ERROR = "ERROR_10008";

    String USER_CHAIN_KEY_NOT_EXIST_ERROR = "ERROR_10009";


    String TASK_ZK_MONITOR_START = "TASK_10001";

    String TASK_ZK_MONITOR_NODE_ACCESS_INFO = "TASK_10002";

    String TASK_NODE_MONITOR_START = "TASK_10003";

    String TASK_NODE_HEARTBEAT_INFO_CHANGE = "TASK_10004";

    String TASK_NODE_HEARTBEAT_COMMITTER_CHANGED = "TASK_10005";

    String TASK_NODE_HEARTBEAT_INFO_DEBUG = "TASK_10006";

    String TASK_REDIS_UPDATE_START = "TASK_10007";

    String TASK_REDIS_UPDATE_ERROR = "TASK_10008";

}
